# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 鍊金Mage
email: alchemy@posetmage.com
description: >- # this means to ignore newlines until "baseurl:"
    大腦是一個賢者之石，充滿無限可能

url: "https://alchemy.posetmage.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/Daily" # the subpath of your site, e.g. /blog

repository: lalchemymage/Daily

social:
  - platform: envelope
    url: mailto:alchemy@posetmage.com
  - platform: youtube
    url: https://youtube.com/@alchemymage
  - platform: facebook
    url: https://facebook.com/alchemymage
  - platform: twitter
    url: https://twitter.com/alchemymage
  - platform: medium
    url: https://medium.com/@alchemymage
  - platform: threads
    url: https://threads.net/alchemy.mage

includes_dir: _shared/_includes
layouts_dir: _shared/_layouts
site_favicon: favicon.ico

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-external-links
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-category-pages
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
